### ISSUE TITLE
[Suggestion] Check some file for circle token

### ISSUE THREAD

**Issue by JustinAiken** [nifengle/circle_plugin#1]
Instead of having to fill in `circle_token = ''`,
it could read it from somewhere like `/users/$(whoami)/.circle` or `/users/$(whoami)/Library/Application\ Support/bitbar/config/circle`

That way there wouldn't need to be any direct editing of the `circle.5s.py` any time it's updated

**Comment by nifengle** [comment]
Good suggestion. Implemented.
